services:
  - type: web
    name: ai-recommendation-api-1
    env: python
    plan: free
    region: singapore
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
